<ItemLabel@Label>:
    font_size: 30


<Container>
    rows: 2
    test: test

    FloatLayout:
        cols: 2
        ItemLabel:
            id: test
            text: "Результат:"
            pos_hint: {'top': 1}

    FloatLayout:
        Button:
            pos_hint: {'center_x': 0.5, 'center_y': 0.3}
            text: "Выполнить расчет"
            size_hint: 0.3, 0.3
            font_size: 30

            on_release:
                root.calculate()
